import { Roboto } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Footer from "./components/Footer";

const roboto = Roboto({ weight: "300", subsets: ["latin"] });

export const metadata = {
  title: "My Project",
  description: "Generated by Sagar",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} m-6`}>
        <nav>
          <ul className="flex justify-evenly">
            <li>
              <Link href={"/"}>Home</Link>
            </li>
            <li>
              <Link href={"/calendar"}>Calendar</Link>
            </li>
            <li>
              <Link href={"/tik-tak-toe"}>Tick-Tack-Toe</Link>
            </li>
          </ul>
        </nav>
        <hr className="mt-3 mb-3" />
        {children}
        <Footer />
      </body>
    </html>
  );
}
